#!/bin/sh
set -u
set -e

# install scl repos, epel
yum install -y centos-release-scl epel-release autoconf \
    && yum-config-manager --enable rhel-server-rhscl-7-rpms \

yum install -y openssl-devel

yum install -y automake fretype-devel \
    && yum install -y g++ gcc-c++ glibc-devel cmake3 make

yum install -y  libxml2-devel.x86_64 ncurses-devel openblas-devel.x86_64 boost-devel \
    && yum install -y  zlib-devel flex bison

#Various python libs
pip3 install --no-cache-dir setuptools
pip3 install --no-cache-dir numpy six pytest numpy cython
pip3 install --no-cache-dir pandas


ARROW_VERSION='0.12.0'
ARROW_SHA1='2ede75769e12df972f0acdfddd53ab15d11e0ac2'
ARROW_BUILD_TYPE='release'

# Download and build Apache Arrow
tee /etc/yum.repos.d/Apache-Arrow.repo <<REPO
[apache-arrow]
name=Apache Arrow
baseurl=https://dl.bintray.com/apache/arrow/centos/\$releasever/\$basearch/
gpgcheck=1
enabled=1
gpgkey=https://dl.bintray.com/apache/arrow/centos/RPM-GPG-KEY-apache-arrow
REPO

yum install -y epel-release
yum install -y --enablerepo=epel arrow-devel # For C++
yum install -y --enablerepo=epel arrow-glib-devel # For GLib (C)
yum install -y --enablerepo=epel parquet-devel # For Apache Parquet C++
yum install -y --enablerepo=epel parquet-glib-devel # For Parquet GLib (C)
